package com.Ameender.qurantracker.ui

data class AppStrings(
    val home: String,
    val dashboard: String,
    val hizb: String,
    val hizbRub: String,
    val juz: String,
    val surah: String,
    val quran: String,
    val stats: String,
    val agenda: String,
    val quranTracker: String,
    val mushaf: String,
    val hafsMedina: String,
    val warshMuhammadi: String,
    val tableOfContents: String,
    val allChapters: String,
    val thirtyAjza: String,
    val sixtyAhzaab: String,
    val bookmarks: String,
    val noBookmarks: String,
    val savedPlaces: String,
    val hifzScore: String,
    val hifzScoreSubtitle: String,
    val scoreRange: String,
    val scoreRangeSubtitle: String,
    val readingJourney: String,
    val quranInDays: String,
    val noEndGoal: String,
    val readingPlan: String,
    val khatmaAndAgenda: String,
    val khatma: String,
    val makeReadingPlan: String,
    val viewPlanning: String,
    val tasbih: String,
    val tasbihLater: String,
    val qibla: String,
    val qiblaLater: String,
    val media: String,
    val defaultReciter: String,
    val offline: String,
    val downloadsLater: String,
    val groups: String,
    val groupsSubtitle: String,
    val account: String,
    val accountSubtitle: String,
    val appearance: String,
    val darkTheme: String,
    val lightTheme: String,
    val language: String,
    val dailyGoal: String,
    val perDay: String,
    val today: String,
    val dailyGoalReached: String,
    val remainingToday: String,
    val completed: String,
    val quickCheckIn: String,
    val planningToday: String,
    val noPlanningToday: String,
    val moreInAgenda: String,
    val wholeQuranInDays: String,
    val aheadOfSchedule: String,
    val behindRub: String,
    val onSchedule: String,
    val done: String,
    val donePartsOfRub: String,
    val plannedUntilToday: String,
    val journeyRingHint: String,
    val progress: String,
    val actions: String,
    val week: String,
    val month: String,
    val streak: String,
    val days: String,
    val motivationPoints: String,
    val pointsShort: String,
    val points: String,
    val newLevelReached: String,
    val pointsToNextLevel: String,
    val bonus: String,
    val streakGoal: String,
    val latest: String,
    val appPointsDisclaimer: String,
    val fireStreak: String,
    val hifzOverview: String,
    val noHifzScores: String,
    val reviewFirst: String,
    val noLowScores: String,
    val strong: String,
    val noStrongScores: String,
    val repeatDue: String,
    val repeatDueSubtitle: String,
    val noRepeatAdvice: String,
    val lateDays: String,
    val tomorrow: String,
    val inDays: String,
    val planned: String,
    val read: String,
    val memorized: String,
    val readCountSummary: String,
    val ayahs: String,
    val timesRead: String,
    val hifz: String,
    val hifzScoreLabel: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val mark: String,
    val oneMoreTime: String,
    val markSurahReadQuestion: String,
    val surahAlreadyReadQuestion: String,
    val markSurahMemorizedQuestion: String,
    val surahAlreadyMemorizedQuestion: String,
    val hifzScoreQuestion: String,
    val dutchSelected: String,
    val englishSelected: String,
    val arabicSelected: String,
    val frenchSelected: String
)

object AppText {
    fun strings(language: String): AppStrings = when (language) {
        "ar" -> arabic
        "en" -> english
        else -> dutch
    }

    fun languageLabel(language: String, currentLanguage: String): String {
        val strings = strings(currentLanguage)
        return when (language) {
            "ar" -> strings.arabicSelected
            "en" -> strings.englishSelected
            "fr" -> strings.frenchSelected
            else -> strings.dutchSelected
        }
    }

    private val dutch = AppStrings(
        home = "Home",
        dashboard = "Dashboard",
        hizb = "Hizb",
        hizbRub = "Hizb & Rub",
        juz = "Juz",
        surah = "Soera",
        quran = "Quran",
        stats = "Stats",
        agenda = "Agenda",
        quranTracker = "Quran Tracker",
        mushaf = "Mushaf",
        hafsMedina = "Hafs - Medina",
        warshMuhammadi = "Warsh - Muhammadi",
        tableOfContents = "Inhoudsopgave",
        allChapters = "Alle hoofdstukken",
        thirtyAjza = "30 ajza",
        sixtyAhzaab = "60 ahzaab",
        bookmarks = "Bladwijzers",
        noBookmarks = "Nog geen bladwijzers",
        savedPlaces = "opgeslagen plekken",
        hifzScore = "Hifz-score 0-100",
        hifzScoreSubtitle = "Kleurtint voor soera, hizb en juz",
        scoreRange = "Score bereik instellen",
        scoreRangeSubtitle = "Geef meerdere items dezelfde score",
        readingJourney = "Leesreis",
        quranInDays = "Quran in %s dagen",
        noEndGoal = "Nog geen einddoel actief",
        readingPlan = "Leesplanning",
        khatmaAndAgenda = "Khatma en agenda",
        khatma = "Khatma",
        makeReadingPlan = "Maak een leesplan",
        viewPlanning = "Bekijk je planning",
        tasbih = "Tasbih",
        tasbihLater = "Teller komt later",
        qibla = "Gebedsrichting",
        qiblaLater = "Qibla komt later",
        media = "Media",
        defaultReciter = "Standaard reciteur",
        offline = "Offline",
        downloadsLater = "Downloads komen later",
        groups = "Groepen",
        groupsSubtitle = "Maak een leesgroep met deelcode",
        account = "Account",
        accountSubtitle = "Optioneel inloggen of zonder account verder",
        appearance = "Uiterlijk",
        darkTheme = "Donker thema",
        lightTheme = "Licht thema",
        language = "Taal",
        dailyGoal = "Dagelijkse doel",
        perDay = "per dag",
        today = "Vandaag",
        dailyGoalReached = "Dagdoel gehaald",
        remainingToday = "Nog %s %s te gaan",
        completed = "Voltooid",
        quickCheckIn = "Snelle check-in",
        planningToday = "Planning vandaag",
        noPlanningToday = "Geen items gepland voor vandaag.",
        moreInAgenda = "meer in Agenda",
        wholeQuranInDays = "Hele Quran in %s dagen",
        aheadOfSchedule = "voor op schema",
        behindRub = "%s rub achter",
        onSchedule = "op schema",
        done = "gedaan",
        donePartsOfRub = "%s van 240 rub-delen",
        plannedUntilToday = "Gepland tot vandaag: %s/240",
        journeyRingHint = "Groene ring is gedaan, lichte ring is planning.",
        progress = "Progressie",
        actions = "acties",
        week = "Week",
        month = "Maand",
        streak = "Streak",
        days = "dagen",
        motivationPoints = "Motivatiepunten",
        pointsShort = "pt",
        points = "punten",
        newLevelReached = "Nieuw level bereikt",
        pointsToNextLevel = "Nog %s punten tot volgende level",
        bonus = "Bonus",
        streakGoal = "streak/doel",
        latest = "Laatste",
        appPointsDisclaimer = "App-punten voor motivatie, niet als religieuze beloning.",
        fireStreak = "Vuurreeks",
        hifzOverview = "Hifz-overzicht",
        noHifzScores = "Nog geen Hifz-scores. Stel een bereik in of houd een item lang vast.",
        reviewFirst = "Herhaal eerst",
        noLowScores = "Geen lage scores gevonden.",
        strong = "Sterk",
        noStrongScores = "Nog geen sterke scores.",
        repeatDue = "Te herhalen",
        repeatDueSubtitle = "Gebaseerd op Hifz-score en laatste scoremoment",
        noRepeatAdvice = "Nog geen herhaaladvies. Geef eerst Hifz-scores.",
        lateDays = "%s dagen te laat",
        tomorrow = "morgen",
        inDays = "over %s dagen",
        planned = "Gepland",
        read = "Gelezen",
        memorized = "gememoriseerd",
        readCountSummary = "%s/114 gelezen · %s/114 gememoriseerd",
        ayahs = "ayah's",
        timesRead = "%sx gelezen",
        hifz = "Hifz",
        hifzScoreLabel = "Hifz-score",
        save = "Opslaan",
        cancel = "Annuleren",
        delete = "Verwijderen",
        mark = "Markeren",
        oneMoreTime = "Nog een keer",
        markSurahReadQuestion = "Wil je %s markeren als gelezen?",
        surahAlreadyReadQuestion = "Je hebt %s al %s keer gelezen. Wat wil je doen?",
        markSurahMemorizedQuestion = "Wil je %s markeren als gememoriseerd?",
        surahAlreadyMemorizedQuestion = "Je hebt %s al gememoriseerd. Wat wil je doen?",
        hifzScoreQuestion = "Hoe goed ken je deze soera uit je hoofd?",
        dutchSelected = "Nederlands geselecteerd",
        englishSelected = "Engels geselecteerd",
        arabicSelected = "Arabisch geselecteerd",
        frenchSelected = "Frans geselecteerd"
    )

    private val english = dutch.copy(
        home = "Home",
        dashboard = "Dashboard",
        hizbRub = "Hizb & Rub",
        surah = "Surah",
        quran = "Quran",
        stats = "Stats",
        agenda = "Agenda",
        tableOfContents = "Contents",
        allChapters = "All chapters",
        thirtyAjza = "30 ajza",
        sixtyAhzaab = "60 ahzaab",
        bookmarks = "Bookmarks",
        noBookmarks = "No bookmarks yet",
        savedPlaces = "saved places",
        hifzScore = "Hifz score 0-100",
        hifzScoreSubtitle = "Color tint for surah, hizb and juz",
        scoreRange = "Set score range",
        scoreRangeSubtitle = "Give multiple items the same score",
        readingJourney = "Reading journey",
        quranInDays = "Quran in %s days",
        noEndGoal = "No end goal active yet",
        readingPlan = "Reading plan",
        khatmaAndAgenda = "Khatma and agenda",
        makeReadingPlan = "Create a reading plan",
        viewPlanning = "View your planning",
        tasbihLater = "Counter comes later",
        qibla = "Prayer direction",
        qiblaLater = "Qibla comes later",
        defaultReciter = "Default reciter",
        downloadsLater = "Downloads come later",
        groups = "Groups",
        groupsSubtitle = "Create a reading group with a share code",
        accountSubtitle = "Optional login or continue without account",
        appearance = "Appearance",
        darkTheme = "Dark theme",
        lightTheme = "Light theme",
        language = "Language",
        dailyGoal = "Daily goal",
        perDay = "per day",
        dailyGoalReached = "Daily goal reached",
        remainingToday = "%s %s left",
        completed = "Completed",
        quickCheckIn = "Quick check-in",
        planningToday = "Today's planning",
        noPlanningToday = "No items planned for today.",
        moreInAgenda = "more in Agenda",
        wholeQuranInDays = "Whole Quran in %s days",
        aheadOfSchedule = "ahead of schedule",
        behindRub = "%s rub behind",
        onSchedule = "on schedule",
        done = "done",
        donePartsOfRub = "%s of 240 rub parts",
        plannedUntilToday = "Planned until today: %s/240",
        journeyRingHint = "Green ring is done, light ring is planned.",
        progress = "Progress",
        actions = "actions",
        month = "Month",
        days = "days",
        motivationPoints = "Motivation points",
        points = "points",
        newLevelReached = "New level reached",
        pointsToNextLevel = "%s points to next level",
        streakGoal = "streak/goal",
        latest = "Latest",
        appPointsDisclaimer = "App points are for motivation, not religious reward.",
        fireStreak = "Fire streak",
        hifzOverview = "Hifz overview",
        noHifzScores = "No Hifz scores yet. Set a range or long-press an item.",
        reviewFirst = "Review first",
        noLowScores = "No low scores found.",
        strong = "Strong",
        noStrongScores = "No strong scores yet.",
        repeatDue = "Due for review",
        repeatDueSubtitle = "Based on Hifz score and latest score moment",
        noRepeatAdvice = "No review advice yet. Add Hifz scores first.",
        lateDays = "%s days late",
        tomorrow = "tomorrow",
        inDays = "in %s days",
        planned = "Planned",
        read = "Read",
        memorized = "memorized",
        readCountSummary = "%s/114 read · %s/114 memorized",
        ayahs = "ayahs",
        timesRead = "%sx read",
        hifzScoreLabel = "Hifz score",
        save = "Save",
        cancel = "Cancel",
        delete = "Delete",
        mark = "Mark",
        oneMoreTime = "One more time",
        markSurahReadQuestion = "Do you want to mark %s as read?",
        surahAlreadyReadQuestion = "You have read %s %s times. What do you want to do?",
        markSurahMemorizedQuestion = "Do you want to mark %s as memorized?",
        surahAlreadyMemorizedQuestion = "You already memorized %s. What do you want to do?",
        hifzScoreQuestion = "How well do you know this surah by heart?",
        dutchSelected = "Dutch selected",
        englishSelected = "English selected",
        arabicSelected = "Arabic selected",
        frenchSelected = "French selected"
    )

    private val arabic = dutch.copy(
        home = "الرئيسية",
        dashboard = "لوحة المتابعة",
        hizb = "حزب",
        hizbRub = "الحزب والربع",
        juz = "جزء",
        surah = "السور",
        quran = "القرآن",
        stats = "الإحصاءات",
        agenda = "الجدول",
        quranTracker = "متتبع القرآن",
        mushaf = "المصحف",
        hafsMedina = "حفص - المدينة",
        warshMuhammadi = "ورش - المحمدي",
        tableOfContents = "الفهرس",
        allChapters = "كل السور",
        thirtyAjza = "30 جزءا",
        sixtyAhzaab = "60 حزبا",
        bookmarks = "العلامات المرجعية",
        noBookmarks = "لا توجد علامات بعد",
        savedPlaces = "مواضع محفوظة",
        hifzScore = "درجة الحفظ 0-100",
        hifzScoreSubtitle = "لون للسورة والحزب والجزء",
        scoreRange = "تعيين نطاق الدرجة",
        scoreRangeSubtitle = "أعط عدة عناصر الدرجة نفسها",
        readingJourney = "رحلة القراءة",
        quranInDays = "القرآن في %s يوم",
        noEndGoal = "لا يوجد هدف نهائي بعد",
        readingPlan = "خطة القراءة",
        khatmaAndAgenda = "الختمة والجدول",
        makeReadingPlan = "أنشئ خطة قراءة",
        viewPlanning = "اعرض جدولك",
        tasbih = "التسبيح",
        tasbihLater = "العداد لاحقا",
        qibla = "اتجاه القبلة",
        qiblaLater = "القبلة لاحقا",
        media = "الصوتيات",
        defaultReciter = "القارئ الافتراضي",
        offline = "بدون إنترنت",
        downloadsLater = "التنزيلات لاحقا",
        groups = "المجموعات",
        groupsSubtitle = "أنشئ مجموعة قراءة برمز مشاركة",
        account = "الحساب",
        accountSubtitle = "تسجيل اختياري أو المتابعة بدون حساب",
        appearance = "المظهر",
        darkTheme = "الوضع الداكن",
        lightTheme = "الوضع الفاتح",
        language = "اللغة",
        dailyGoal = "الهدف اليومي",
        perDay = "في اليوم",
        today = "اليوم",
        dailyGoalReached = "تم تحقيق هدف اليوم",
        remainingToday = "باقي %s %s",
        completed = "مكتمل",
        quickCheckIn = "تسجيل سريع",
        planningToday = "جدول اليوم",
        noPlanningToday = "لا توجد عناصر مخططة اليوم.",
        moreInAgenda = "أخرى في الجدول",
        wholeQuranInDays = "القرآن كاملا في %s يوم",
        aheadOfSchedule = "متقدم على الخطة",
        behindRub = "متأخر %s ربع",
        onSchedule = "على الخطة",
        done = "تم",
        donePartsOfRub = "%s من 240 ربع",
        plannedUntilToday = "المخطط حتى اليوم: %s/240",
        journeyRingHint = "الحلقة الخضراء منجزة، والفاتحة هي الخطة.",
        progress = "التقدم",
        actions = "إجراءات",
        week = "الأسبوع",
        month = "الشهر",
        streak = "السلسلة",
        days = "أيام",
        motivationPoints = "نقاط التحفيز",
        pointsShort = "نقطة",
        points = "نقاط",
        newLevelReached = "تم الوصول إلى مستوى جديد",
        pointsToNextLevel = "باقي %s نقطة للمستوى التالي",
        bonus = "مكافأة",
        streakGoal = "سلسلة/هدف",
        latest = "الأخير",
        appPointsDisclaimer = "نقاط التطبيق للتحفيز وليست ثوابا شرعيا.",
        fireStreak = "سلسلة النشاط",
        hifzOverview = "ملخص الحفظ",
        noHifzScores = "لا توجد درجات حفظ بعد. عيّن نطاقا أو اضغط مطولا على عنصر.",
        reviewFirst = "راجع أولا",
        noLowScores = "لا توجد درجات منخفضة.",
        strong = "قوي",
        noStrongScores = "لا توجد درجات قوية بعد.",
        repeatDue = "للمراجعة",
        repeatDueSubtitle = "بناء على درجة الحفظ وآخر تقييم",
        noRepeatAdvice = "لا توجد نصيحة مراجعة بعد. أضف درجات الحفظ أولا.",
        lateDays = "متأخر %s يوم",
        tomorrow = "غدا",
        inDays = "بعد %s أيام",
        planned = "مخطط",
        read = "مقروء",
        memorized = "محفوظ",
        readCountSummary = "%s/114 مقروء · %s/114 محفوظ",
        ayahs = "آيات",
        timesRead = "قُرئت %s مرة",
        hifz = "الحفظ",
        hifzScoreLabel = "درجة الحفظ",
        save = "حفظ",
        cancel = "إلغاء",
        delete = "حذف",
        mark = "تحديد",
        oneMoreTime = "مرة أخرى",
        markSurahReadQuestion = "هل تريد تحديد %s كمقروءة؟",
        surahAlreadyReadQuestion = "لقد قرأت %s %s مرة. ماذا تريد أن تفعل؟",
        markSurahMemorizedQuestion = "هل تريد تحديد %s كمحفوظة؟",
        surahAlreadyMemorizedQuestion = "لقد حفظت %s بالفعل. ماذا تريد أن تفعل؟",
        hifzScoreQuestion = "ما مدى معرفتك بهذه السورة عن ظهر قلب؟",
        dutchSelected = "تم اختيار الهولندية",
        englishSelected = "تم اختيار الإنجليزية",
        arabicSelected = "تم اختيار العربية",
        frenchSelected = "تم اختيار الفرنسية"
    )
}
